# Site settings
title: "J.S LEE Portfolio"
name: "J.S"
email: "dlwjdtn5624@naver.com"
description: >-
  시니어 풀스택 개발자 J.S의 포트폴리오. 10년 이상의 실무 경험과 
  Spring Boot, React, AWS 전문성을 바탕으로 다양한 프로젝트를 성공적으로 완료했습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dlwjdtn535.github.io" # the base hostname & protocol for your site
twitter_username: dlwjdtn535
github_username: dlwjdtn535
linkedin_username: dlwjdtn535

# Author information
author:
  name: "J.S"
  email: "dlwjdtn5624@naver.com"
  bio: "10년 이상의 실무 경험을 가진 시니어 풀스택 개발자"
  github: "dlwjdtn535"
  linkedin: "dlwjdtn535"
  twitter: "dlwjdtn535"

# SEO settings
lang: ko_KR
locale: ko_KR
timezone: Asia/Seoul

# Social media
social:
  name: J.S LEE
  links:
    - https://github.com/dlwjdtn535
    - https://linkedin.com/in/dlwjdtn535
    - https://twitter.com/dlwjdtn535

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag

# Feed settings
feed:
  excerpt_only: true

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - src/
  - vite.config.ts
  - tsconfig.json
  - .prettierrc.js
  - .prettierignore
  - .eslintrc.js
  - .vscode/
  - tailwind.config.js
  - postcss.config.js
  - index-dev.html
  - .git/
  - .github/
  - vendor/

# Include files that start with underscore and important files
include:
  - _layouts
  - .htaccess
  - robots.txt
  - _pages
  - js/react-build
  - public

# SEO tag settings
tag_page_layout: tag_page
tag_page_dir: tag

# Additional settings
future: false
show_drafts: false
unpublished: false

# Copy Vite build assets
defaults:
  - scope:
      path: "js/react-build"
    values:
      layout: null
      sitemap: false
  - scope:
      path: ""
    values:
      layout: "default"
      sitemap: true

# Static file serving
static_files:
  - "*.woff"
  - "*.woff2"
  - "*.ttf"
  - "*.otf"
