# Site settings
title: "개발자 포트폴리오"
description: "Jekyll + React + TypeScript + Tailwind CSS로 제작된 현대적인 포트폴리오 웹사이트"
url: "https://dlwjdtn535.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - pnpm-lock.yaml
  - src/
  - vite.config.ts
  - tsconfig.json
  - .prettierrc.js
  - .prettierignore
  - .eslintrc.js
  - .vscode/
  - tailwind.config.js
  - postcss.config.js
  - index-dev.html

# Include files that start with underscore
include:
  - _layouts
